name: EasyScan
description: A Crossplatform document scanning app that can convert images to pdf in a simple tap.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.0


flutter:
  uses-material-design: true
